name: Simple GitHub Action

on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Hello, GitHub Actions! Test"
