name: Simple GitHub Action

on:
  repository_dispatch:
    types:
      - manual-trigger

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Hello, GitHub Actions! Test"
